<a href="https://colab.research.google.com/github/alhnklc/Machine-Learning-Classifier-use-iris-data-set/blob/main/Ir%C4%B1sProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount("/gdrive")

Mounted at /gdrive


In [2]:
import os
os.chdir("/gdrive/MyDrive/Makine Öğrenmesi/IrısProject/")
!ls

IrısProject.ipynb  Iris.xls


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

>Read excel file and assign to data variable

In [4]:
data = pd.read_excel("Iris.xls")
data

sepal length  sepal width  petal length  petal width            iris
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

# **data variable separate as x and y**

>x = sepal length, sepal, width, petal length, petal width columns

>y = iris column

In [87]:
x = data.iloc[:,:4]
y = data.iloc[:,4:]
x

sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [31]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)
y_test

iris
114   Iris-virginica
62   Iris-versicolor
33       Iris-setosa
107   Iris-virginica
7        Iris-setosa
100   Iris-virginica
40       Iris-setosa
86   Iris-versicolor
76   Iris-versicolor
71   Iris-versicolor
134   Iris-virginica
51   Iris-versicolor
73   Iris-versicolor
54   Iris-versicolor
63   Iris-versicolor
37       Iris-setosa
78   Iris-versicolor
90   Iris-versicolor
45       Iris-setosa
16       Iris-setosa
121   Iris-virginica
66   Iris-versicolor
24       Iris-setosa
8        Iris-setosa
126   Iris-virginica
22       Iris-setosa
44       Iris-setosa
97   Iris-versicolor
93   Iris-versicolor
26       Iris-setosa
137   Iris-virginica
84   Iris-versicolor
27       Iris-setosa
127   Iris-virginica
132   Iris-virginica
59   Iris-versicolor
18       Iris-setosa
83   Iris-versicolor
61   Iris-versicolor
92   Iris-versicolor
112   Iris-virginica
2        Iris-setosa
141   Iris-virginica
43       Iris-setosa
10       Iris-setosa
60   Iris-versicolor
116   Iris-virginica
144   Iris-virginica
119   Iris-virginica
108   Iris-virginica

In [18]:
from sklearn.linear_model import LogisticRegression
logistic_reg = LogisticRegression()

In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

>Preprocessing x_train, x_test

In [21]:
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)


*   1.X_train and y_train fit  as logistic regression
*   2.X_test predict and assign to as log_y_predict




In [23]:
logistic_reg.fit(X_train, y_train)
log_y_predict = logistic_reg.predict(X_test)
log_y_predict

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype=object)

#compare y_test and log_y_predict use with confusion matrix 

In [63]:
cm1 = confusion_matrix(y_test, log_y_predict)
cm1

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  0, 15]])

#KNN



1.   import KNN algorithm as n_neighbors=4 and metric="minkowski"
2.   fit X_train and y_train 
3.   predict X_test
4.   compare y_test and knn_y_predict use with confusion_matrix


In [56]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4, metric="minkowski")

In [57]:
knn.fit(X_train, y_train)
knn_y_predict = knn.predict(X_test)
knn_y_predict

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica'],
      dtype=object)

In [62]:
cm2 = confusion_matrix(y_test, knn_y_predict)
cm2

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  1, 14]])

#Support Vector Machine

1.   import Support Vector Machine
2.   fit X_train and y_train 
3.   predict X_test
4.   compare y_test and svc_y_predict use with confusion_matrix

In [59]:
from sklearn.svm import SVC
svc = SVC()

In [60]:
svc.fit(X_train, y_train)
svc_y_predict = svc.predict(X_test)
svc_y_predict

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica'],
      dtype=object)

In [61]:
cm3 = confusion_matrix(y_test, svc_y_predict)
cm3

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  1, 14]])

#Naive Bayes

1.   import GaussianNB
2.   fit X_train and y_train 
3.   predict X_test
4.   compare y_test and nb_y_predict use with confusion_matrix

In [65]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()

In [66]:
nb.fit(X_train, y_train)
nb_y_predict = nb.predict(X_test)
nb_y_predict

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica'],
      dtype='<U15')

In [67]:
cm4 = confusion_matrix(y_test, nb_y_predict)
cm4

array([[16,  0,  0],
       [ 0, 17,  2],
       [ 0,  1, 14]])

#Decision Tree

1.   import Decision Tree algorithm as criterion="entropy"
2.   fit X_train and y_train 
3.   predict X_test
4.   compare y_test and dt_y_predict use with confusion_matrix

In [71]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion="entropy")


In [72]:
dt.fit(X_train, y_train)
dt_y_predict = dt.predict(X_test)
dt_y_predict

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype=object)

In [75]:
cm5 = confusion_matrix(y_test, dt_y_predict)
cm5

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  1, 14]])

#Random Decision Tree

1.   import Random Decision Tree algorithm as n_estimators=10 and criterion="entropy"
2.   fit X_train and y_train 
3.   predict X_test
4.   compare y_test and rfc_y_predict use with confusion_matrix

In [78]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10, criterion="entropy")

In [79]:
rfc.fit(X_train, y_train)
rfc_y_predict = rfc.predict(X_test)
rfc_y_predict

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype=object)

In [80]:
cm6 = confusion_matrix(y_test, rfc_y_predict)
cm6

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  0, 15]])